Fix JSON output, add tests (#12)

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -289,17 +289,27 @@ jobs:
                   DB_PASSWORD: ''
                   DB_HOST: 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
 
-            - name: Checkout Ginger-MO
+            - name: Checkout Ginger MO
               uses: actions/checkout@v3
               with:
                   path: 'src/wp-content/plugins/ginger-mo'
 
-            - name: Load Ginger-MO for tests
+            - name: Load Ginger MO for tests
               run: |
                   echo "require dirname( __DIR__, 3 ) . '/src/wp-content/plugins/ginger-mo/ginger-mo.php';" >> tests/phpunit/includes/bootstrap.php
 
-            - name: Run tests
+            - name: Run tests (PHP format)
               run: vendor/bin/phpunit --group=l10n,i18n,pomo
+
+            - name: Run tests (JSON format)
+              run: |
+                  echo "add_filter( 'ginger_mo_preferred_format', static function () { return 'json'; } );" >> tests/phpunit/includes/bootstrap.php
+                  vendor/bin/phpunit --group=l10n,i18n,pomo
+
+            - name: Run tests (MO format)
+              run: |
+                  echo "add_filter( 'ginger_mo_preferred_format', static function () { return 'mo'; } );" >> tests/phpunit/includes/bootstrap.php
+                  vendor/bin/phpunit --group=l10n,i18n,pomo
 
     performance-tests:
         name: 'Performance Tests (trunk)'
@@ -368,9 +378,10 @@ jobs:
                   BASE_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.base_ref }}
                   BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
 
+            # Run tests without causing job to fail if they don't pass (e.g. because of env issues).
             - name: Run tests for base
               run: |
-                  npm run test:performance
+                  npm run test:performance || true
                   if [ -f "{{ env.WP_ARTIFACTS_PATH }}/performance-results.json" ]; then
                     mv ${{ env.WP_ARTIFACTS_PATH }}/performance-results.json ${{ runner.temp }}/results_before.json
                   fi;
